services:
  db:
    image: postgres:15 
    container_name: leads_agent_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-leads_db}
    ports:
      - "${POSTGRES_PORT:-5431}:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: 